version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: homemadefood-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: homemadefood_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: homemadefood-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: homemadefood-backend
    restart: unless-stopped
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres123
      DATABASE_NAME: homemadefood_db
      JWT_SECRET: dev-secret-key-change-in-production
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    command: npm run start:dev

volumes:
  postgres_data:
  redis_data: